baseURL = "/"
languageCode = "en-us"
#languageCode = "ch-zn"
title = "CHENURE"
theme = "hello-friend-ng"
paginate = 10

enableRobotsTXT = true
enableEmoji     = true

[blackfriday]
  hrefTargetBlank = true

[params]

  # "light" or "dark"
  defaultTheme = "dark"
  
  # Subtitle for home
  homeSubtitle = "奥特曼要打小怪兽？！:smile:"
  
  # Enable to show reading time in minutes for posts
  showReadingTime = false

[author]
  name = "CHEN"
  
[taxonomies]
	tag      = "tags"
    category = "categories" 
	
[params.footer]
    trademark = true
    copyright = true
    author = true

[languages]
  [languages.en]
    title = "CHENURE"
    subtitle = "Less Is More"
	author = "true"
   
    #writtenBy = "Written by"
    #readMore = "Read more"
    #readOtherPosts = "Read other posts"
    #newerPosts = "Newer posts"
    #olderPosts = "Older posts"
    #minuteReadingTime = "min read"

    [[menu.main]]
	  identifier = "blog"
	  name       = "Blog"
	  url        = "/posts"
	  
	[[menu.main]]
    identifier = "about"
    name       = "About"
    url        = "/about"

