baseURL = "/"
#languageCode = "en-us"
languageCode = "ch-zn"
title = "CHENURE"
theme = "hello-friend-ng"
paginate = 10

[params]

  # "light" or "dark"
  defaultTheme = "dark"
  
  # Subtitle for home
  homeSubtitle = "Love && Peace"
  
  # Metadata mostly used in document's head
  description = "小怪兽？！"
  keywords = "blog"
  images = [""]
  
  # Enable to show reading time in minutes for posts
  showReadingTime = false
  
[permalinks]
  posts = "/posts/:year/:month/:title/"

[author]
  name = "CHEN"

[taxonomies]
    category = "blog"
    tag      = "tags"
    series   = "series"
	
[params.footer]
    trademark = true
    rss = true
    copyright = true
    author = true

    topText = []
    bottomText = [
      "Powered by <a href=\"http://gohugo.io\">Hugo</a>",
      "Made with &#10084; by <a href=\"https://github.com/rhazdon\">Djordje Atlialp</a>"
    ]

[languages]
  [languages.en]
    title = "CHNURE"
    subtitle = "奥特曼要打小怪兽？！"
    keywords = ""
    copyright = ""
    writtenBy = "Written by"
    readMore = "Read more"
    readOtherPosts = "Read other posts"
    newerPosts = "Newer posts"
    olderPosts = "Older posts"
    minuteReadingTime = "min read"

    [languages.en.params.logo]
      logoText = "hello friend"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

    [[menu.main]]
	  identifier = "blog"
	  name       = "Blog"
	  url        = "/posts"
	  
	[[menu.main]]
    identifier = "about"
    name       = "About"
    url        = "/about"

