baseURL = "/"
#languageCode = "en-us"
languageCode = "ch-zn"
title = "CHENURE"
theme = "hello-friend-ng"
paginate = 10

[author]
	name = "CHEN"

[params]
	# "light" or "dark"
	defaultTheme = "dark"

	# Subtitle for home
	homeSubtitle = "奥特曼要打小怪兽？！"

	dateform        = "Jan 2, 2006"
	dateformShort   = "Jan 2"
	dateformNum     = "2006-01-02"
	dateformNumTime = "2006-01-02 15:04"

	author =true
  
[taxonomies]
	tag      = "tags"
    category = "categories" 
	
[params.footer]
    trademark = true
	rss = true
    copyright = true
    author = true
	topText = []

[languages]
	[languages.en]
		title = "CHENURE"
		subtitle = "Less Is More"
		readOtherPosts = "Read other posts"

	[languages.en.params.logo]
		logoText = "Hello, Friends"
		logoHomeLink = "/"

[menu]
	[[menu.main]]
		identifier = "blog"
		name       = "Blog"
		url        = "/posts"
	  
	[[menu.main]]
		identifier = "about"
		name       = "About"
		url        = "/about"

