baseURL = "/"
title = "CHENURE"
languageCode = "en-us"
theme = "hello-friend-ng"

PygmentsCodeFences = true
PygmentsStyle = "monokai"

paginate = 10
copyright = "Copyright@MonstarLib"

enableEmoji = true

[permalinks]
	posts = "/posts/:year/:month/:title/"

[author]
	name = "CHEN"
	
[taxonomies]
	tag = "tags"
    category = "categories" 

[params]
	# "light" or "dark"
	defaultTheme = "dark"
	enableThemeToggle = true

	# Subtitle for home
	homeSubtitle = "奥特曼要打小怪兽？！于是，小怪兽变成了奥特曼~"
  
	dateform = "Jan 2, 2006"
	dateformShort = "Jan 2"
	dateformNum = "2006-01-02"
	dateformNumTime = "2006-01-02 15:04"
	
	readOtherPosts = "Read other posts"
	
[params.footer]
    trademark = true
	#rss = true
    copyright = true
    author = true
	topText = []
	
[params.favicon.color]
    mask = "#1b1c1d"
    msapplication = "#1b1c1d"
    theme = "#1b1c1d"

[params.logo]
    logoMark     = ">"
    logoText     = "$ cd /home/"
    logoHomeLink = "/"

[[params.social]]
	name = "github"
	url  = "https://github.com/"

[languages]
	[languages.en]
		subtitle = "奥特曼的小怪兽"

[menu]
	[[menu.main]]
		identifier = "blog"
		name = "Blog"
		url = "posts/"
	  
	[[menu.main]]
		identifier = "about"
		name = "About"
		url = "about/"

