baseURL = "/"
#languageCode = "en-us"
languageCode = "ch-zn"
title = "CHENURE"
theme = "hello-friend-ng"
paginate = 10

[params]
  # "light" or "dark"
  defaultTheme = "dark"
  
  # Subtitle for home
  homeSubtitle = "奥特曼要打小怪兽？！"

[author]
  name = "CHEN"
  
[taxonomies]
	tag      = "tags"
    category = "categories" 
	
[params.footer]
    #trademark = true
	rss = true
    copyright = true
    author = true
	topText = []

[languages]
  [languages.en]
    title = "CHENURE"
    subtitle = "Less Is More"
   
    #writtenBy = "Written by"
    #readMore = "Read more"
    readOtherPosts = "Read other posts"
    newerPosts = "Newer posts"
    olderPosts = "Older posts"
    #minuteReadingTime = "min read"
	
	[languages.en.params.logo]
      logoText = "Hello, Friends"
      logoHomeLink = "/"

    [[menu.main]]
	  identifier = "blog"
	  name       = "Blog"
	  url        = "/posts"
	  
	[[menu.main]]
    identifier = "about"
    name       = "About"
    url        = "/about"

